---
title: "summarize contributors"
output: 
    html_document:
        keep_md: yes
params:
    org_name: "ropensci"
    report_start_date: !r as.Date("2018-09-01")
    report_end_date: !r as.Date("2019-09-01")
    bot_gh_users: !r c("web-flow", "ropenscibot")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library("dplyr")
library("magrittr")
source(here::here("R/clean_authors.R"))
options(readr.num_columns = 0)
options(knitr.table.format = 'markdown')
```

```{r report_params}
org_name <- params$org_name
report_start_date <- params$report_start_date
report_end_date <- params$report_end_date
bot_gh_users <- params$bot_gh_users
```

- Github organization: **`r org_name`**.
- Commits were considered from `r report_start_date` to `r report_end_date`.
- Excluded users: `r paste(bot_gh_users, collapse = ", ")`.

```{r result_folder}
result_folder <- here::here("results", glue::glue("{org_name}_{report_start_date}_{report_end_date}"))
dir.create(result_folder, recursive = TRUE, showWarnings = FALSE)
```

```{r clean,message=TRUE}
commits_in_report_period <- here::here("data", glue::glue("commits_{org_name}_{report_start_date}_{report_end_date}.csv")) %>%
    readr::read_csv() %>%
    filter(!author_login %in% bot_gh_users)

cleaned_commits <- commits_in_report_period %>%
    identify_authors_by_name() %>%
    unify_logins_by_email() %>%
    filter(!is.na(author_id))

message(nrow(commits_in_report_period) - nrow(cleaned_commits), " commits were discarded due to being unidentifiable.")
```

```{r num_contributor}
authors <- cleaned_commits %>%
    group_by(author_id, commit_author_name, is_identifiable_by_login) %>%
    summarize(freq = n()) %>%
    group_by(author_id, is_identifiable_by_login) %>%
    summarize(author_name = first(commit_author_name, -freq))

author_summary <- cleaned_commits %>%
    group_by(author_id) %>%
    summarise(
        n_commit = n(),
        n_repo = n_distinct(repo)
    ) %>%
    ungroup() %>%
    inner_join(authors, by = "author_id") %>%
    arrange(-n_repo, -n_commit) %T>%
    readr::write_csv(file.path(result_folder, "authors.csv"))
```

### Top contributors

```{r,echo=TRUE}
author_summary %>% 
    filter(n_commit * n_repo >= 1000) %>% 
    select(author_id, author_name, n_commit, n_repo) %>% 
    knitr::kable()
```


**Total number of contributors in the past year: `r nrow(author_summary)`.**

### Authors by number of repositories they contributed to

```{r authors_by_num_repo}
author_summary %>%
    ungroup() %>%
    arrange(-n_repo) %>%
    mutate(n_repo = cut(
        n_repo,
        breaks = c(0:5, 10, 50, 1000),
        labels = c(as.character(1:5), "6-10", "11-50", "50+")
    )) %>%
    group_by(n_repo) %>%
    summarize(n_author = n()) %>%
    ungroup() %T>%
    readr::write_csv(file.path(result_folder, "authors_by_num_repo.csv")) %>% 
    knitr::kable()
```

### Authors by number of commits they made

```{r authors_by_num_commit}
author_summary %>%
    ungroup() %>%
    arrange(-n_commit) %>%
    mutate(n_commit = cut(
        n_commit,
        breaks = c(0, 1, 5, 10, 100, 1000, 10000),
        labels = c("1", "2-5", "6-10", "11-100", "101-1000", "1000+")
    )) %>%
    group_by(n_commit) %>%
    summarize(n_author = n()) %>%
    ungroup() %T>%
    readr::write_csv(file.path(result_folder, "authors_by_num_commit.csv")) %>% 
    knitr::kable()
```

